### ISSUE TITLE
Any examples for learning a RankSVM and testing?

### ISSUE THREAD

**Issue by LynnHo** [rth/pysofia#10]
I saw a learning example of RankSVM. However, I have no idea how to test it on the new data? Can you provide any examples? Thanks!! @rth

**Comment by TheEdoardo93** [comment]
Hi @LynnHo,
I'm also trying to perform RankSVM ranking model in some manner in Python language. I try out "pysvmlight" software library but it is no longer maintained. I've found this library ("pysofia") but I don't understand several things, e.g., expected input, how to tune parameters of the model, how to do performance evaluation, etc

@rth Can you give us some tips about these topics?
Thanks!

**Comment by rth** [comment]
@LynnHo @TheEdoardo93 I know that the documentation for this package is not great / almost nonexistent. Will try to add a few examples soon.

**Comment by TheEdoardo93** [comment]
Thanks a lot for your answer @rth ;)

In particular, for me it is important to understand these elements:
1) how to train a rankSVM ranking model and how to tune its parameters (i.e., C, cost, ...)
2) how to perform an evaluation of the results obtained (cross validation for finding the "optimal value" for C, evaluation metrics for understand the results, ...)
3) input and output of the main methods
4) how should be formatted the training set and the testing set

**Comment by TheEdoardo93** [comment]
up
