### ISSUE TITLE
Cannot import name _sofia_ml

### ISSUE THREAD

**Issue by hhh920406** [rth/pysofia#5]
Hi, rth. when I import pysofia, there have been a importerror : cannot import name _sofia_ml.

I install pysofia through pip. How can I solve the problem?

**Comment by rth** [comment]
Hi @hhh920406, are you using Windows? The PR #4  might have fixed it. Could you try again, please? Otherwise, try to download the sources (or clone the repository), then run

```
python setup.py develop
```

Thanks for reporting it.

**Comment by hhh920406** [comment]
Thanks for your reply! I use ubantu. After I clone the repository and run setup.py, I can import pysofia successfully!
